# See: https://taskfile.dev/api/

# For generate new .pb.go files need run "task generate"
# but check for program availability "Task"
# for example installation comand on Windows: "winget install Task.Task"
# and for installation on the Go: "go install github.com/go-task/task/v3/cmd/task@latest"

version: "3"

tasks:
  default: # Если не указать конкретную команду, будут выполнены дефолтные
    cmds:  
      - task: generate 
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - protoc -I proto proto/sso/*.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
